"""empty message

Revision ID: 9056149b2820
Revises: 8a4fbd78807f
Create Date: 2021-02-01 03:02:30.635089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9056149b2820'
down_revision = '8a4fbd78807f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    op.create_unique_constraint(None, 'quotes', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotes', type_='unique')
    op.create_table('tests',
    sa.Column('id', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tests_pkey')
    )
    # ### end Alembic commands ###
