"""empty message

Revision ID: 9802ef88834a
Revises: 9056149b2820
Create Date: 2021-02-01 03:33:14.524807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9802ef88834a'
down_revision = '9056149b2820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quotes_id_key', 'quotes', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('quotes_id_key', 'quotes', ['id'])
    # ### end Alembic commands ###
